#!/bin/bash
set -xe
#temp disable
exit 0
cat /etc/dhcp/dhclient.conf | grep 'fixed-address 192.168.254.1;' && exit 0
## fix dhcp
cat >> /etc/dhcp/dhclient.conf << __EOF__
timeout 30;
lease {
interface "eth0";
fixed-address 192.168.254.1;
option subnet-mask 255.255.255.0;
option routers 192.168.254.1;
renew 2 2037/1/12 00:00:01;
rebind 2 2037/1/12 00:00:01;
expire 2 2037/1/12 00:00:01;
}
__EOF__
